class StatusConstant
  PERMISSION_DENIED = "PERMISSION_DENIED"
  INVALID_PARAMS = "INVALID_PARAMS"
  UNAUTHORIZED = "UNAUTHORIZED"
  RESOURCE_NOT_EXIST = "RESOURCE_NOT_EXIST"
  NOT_FOUND = "NOT_FOUND"
end
